/**
 * Shared configuration helpers for harness scripts.
 *
 * Single source of truth: agent names are derived from agent-models.json,
 * so adding a new agent only requires updating that file + creating the
 * agent's .md file.  Every script in .opencode/scripts/ uses this module
 * instead of hardcoding agent lists.
 *
 * Usage (ESM):
 *   import { getAgentNames, getRoot, loadModels, loadRegistry } from './lib/config.mjs';
 *
 * For CommonJS (bin/cli.js), see the inline helper that reads agent-models.json
 * directly — CJS cannot import ESM.
 */

import { readFileSync, existsSync } from 'fs';
import { join, dirname } from 'path';
import { fileURLToPath } from 'url';

const __dirname = dirname(fileURLToPath(import.meta.url));

/** Project root (two levels up from lib/) */
export const ROOT = join(__dirname, '..', '..', '..');

const MODELS_FILE = join(ROOT, '.opencode', 'agent-models.json');
const REGISTRY_FILE = join(ROOT, '.opencode', 'agent-registry.json');
const AGENTS_DIR = join(ROOT, '.opencode', 'agents');
const SKILLS_DIR = join(ROOT, '.opencode', 'skills');

/**
 * Return sorted agent names from agent-models.json (the single source of truth).
 * @returns {string[]}
 */
export function getAgentNames() {
  const models = loadModels();
  return Object.keys(models.agents || {}).sort();
}

/**
 * Load and parse agent-models.json.
 * @returns {{ default_fallback: string[], agents: Record<string, { model: string, fallback: string[] }> }}
 */
export function loadModels() {
  return JSON.parse(readFileSync(MODELS_FILE, 'utf-8'));
}

/**
 * Load and parse agent-registry.json (generated by skill-registry.mjs).
 * @returns {object}
 */
export function loadRegistry() {
  return JSON.parse(readFileSync(REGISTRY_FILE, 'utf-8'));
}

/** @returns {string} */
export function getAgentsDir() { return AGENTS_DIR; }

/** @returns {string} */
export function getSkillsDir() { return SKILLS_DIR; }

/** @returns {string} */
export function getModelsFile() { return MODELS_FILE; }

/** @returns {string} */
export function getRegistryFile() { return REGISTRY_FILE; }
